eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
  application:
    name: product-service

server:
  port: 8084